config/routes.rb
Rails.application.routes.draw do
  get 'page/home'

  get 'page/about'

  get 'page/contact'
  
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root 'page#home'

end

app/models/boc.rb
class Boc < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, :company, :price, presence: true
  validates :content, presence: true, length: { maximum: 300 }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :bocs, dependant:destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  
  before_action :authenticate_user!, only: [:contact,:about]
  
  def home
    @bocs = current_user.bocs.paginate(page: params[:page])
  end

  def about
  end

  def contact
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/bocs/_boc.html.erb
<li id="boc-<%= micropost.id %>">
  <%= link_to gravatar_for(boc.user, size: 50), boc.user %>
  <span class="user"><%= link_to boc.user.name, boc.user %></span>
  <span class="content"><%= boc.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(boc.created_at) %> ago.
  </span>
</li>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Bocs Chile © 2016
  </small>
  <nav>
    <ul>
      <li><%= link_to "Sobre Nosotros", page_about_path   %></li>
      <li><%= link_to "Contacto", page_contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "bocs app", page_home_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
             <% if user_signed_in? %>
               <li><%= link_to "Sobre Bocs", page_about_path %></li>
               <li><%= link_to "Contacto", page_contact_path %></li>
               <li><%= link_to "Bienvenido," , edit_user_registration_path %></li>
               <li><%= link_to "Salir de mi cuenta", destroy_user_session_path, method: :delete %></li>
             <% else %>
                <li><%= link_to "CREA UNA CUENTA", new_user_registration_path %></li>
                <li><%= link_to "Sobre Bocs", page_about_path %></li>
                <li><%= link_to "Contacto", page_contact_path %></li>
                <li><%= link_to "Ingresa a tu cuenta", new_user_session_path %></li>
              <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_railsdefault.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_welcome.html.erb
<% if user_signed_in? %>
<div class="center jumbotron">
  <h1>Bienvenido a BOCS</h1>

  <h2>
    En esta página podrás ingresar BOCS, que serán resueltos por nuestros Bocsers!</h2> 
    <h2>Actualmente estás conectado con tu mail:</h2>
  <p><%= current_user.email %></p><%= link_to 'Editar Usuario', edit_user_registration_path(current_user) %>
  
  <h4><p class="notice"><%= notice %></p></h4>
  <h3><p class="alert"><%= alert %></p></h3>
  
  


<% else %>
<div class="center jumbotron">
  <h1>Bienvenido a BOCS</h1>

  <h2>
    En esta página podrás ingresar BOCS, que serán resueltos por nuestros Bocsers!
  </h2>
  

  <%= link_to "REGISTRATE AHORA!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
  
  <%= link_to "o INGRESA A TU CUENTA", new_user_session_path, class: "btn btn-lg btn-secondary" %>
  
  <h4><p class="notice"><%= notice %></p></h4>
  <h3><p class="alert"><%= alert %></p></h3>
  
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bocs, Aplicación Chilena de Reclamos</title>
    <%= render 'layouts/railsdefault' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/welcome' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/home.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.bocs.any? %>
      <h3>Bocs (<%= @user.bocs.count %>)</h3>
      <ol class="bocs">
        <%= render @bocs %>
      </ol>
      <%= will_paginate @bocs %>
    <% end %>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_user_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "No te has registrado aún? REGÍSTRATE", new_user_registration_path %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Olvidaste tu Contraseña?", new_user_password_path %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>